version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - ./app/:/code/app/
    env_file:
      - ./app/.env
    restart: on-failure
