# Generated by Django 4.1.7 on 2023-02-15 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_track_album_alter_track_song'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('track_number', 'album', 'song')},
        ),
    ]
